# Generated by Django 4.0.6 on 2022-07-13 08:59

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/testimagemodel/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
