# Generated by Django 4.0.6 on 2022-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AddField(
            model_name='service_locator',
            name='center',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
