# Generated by Django 4.0.6 on 2022-07-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_servicelocator'),
    ]

    operations = [
        migrations.AddField(
            model_name='localarea',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.district'),
        ),
    ]
