# Generated by Django 4.0.6 on 2022-07-15 07:05

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/Client/', verbose_name='Image')),
            ],
        ),
    ]
