# Generated by Django 4.0.6 on 2022-07-15 08:23

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/service/', verbose_name='Image')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'service',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.CreateModel(
            name='subService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('sub_image', versatileimagefield.fields.VersatileImageField(upload_to='images/sub service/', verbose_name='Image')),
                ('sub_description', models.TextField()),
                ('main_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service')),
            ],
            options={
                'verbose_name_plural': 'Sub service',
            },
        ),
    ]
